#!/bin/bash

GREEN='\e[0;32m'
RED='\e[0;31m'
RESET='\e[0m'

if [[ $1 == *c* ]]; then
  echo -e "${GREEN}Running Client${RESET}"
elif [[ $1 == *s* ]]; then
  echo -e "${GREEN}Running Server${RESET}"
else
  echo -e "${RED}use -c to run the client \nuse -s to run the server${RESET}"
fi